const gamesData = [
    {
        id: 1,
        title: "Magnets Drag&Drop",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Magnets/contents/",
        banner: "https://www.shutterstock.com/image-vector/science-day-600nw-71929141.jpg",
    },
    {
        id: 2,
        title: "Mario MCQ",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Mario_MCQ/contents/",
        banner: "https://images-cdn.ubuy.co.in/635e1ab163d3200ab81be27a-boy-super-mario-backdrop-5x3-feet-kids.jpg",
    },
    {
        id: 3,
        title: "Gold Mine",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Gold_Miner/contents/",
        banner: "https://media.istockphoto.com/id/908952990/vector/illustration-of-the-treasure-cave-with-a-waterfall-and-chest.jpg?s=612x612&w=0&k=20&c=3Zye5Ts8V5q_UbvvCzjhRxQmqWdt0vo1p6sz8R5uXMc=",
    },
    {
        id: 4,
        title: "Train MCQ",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Train_MCQ/contents/",
        banner: "https://via.placeholder.com/300x200?text=Train+MCQ",
    },
    {
        id: 5,
        title: "BasketBall ",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Final_Activity_Template/BasketBall/contents/",
        banner: "https://img.freepik.com/premium-vector/cheerful-little-kids-playing-basketball-with-big-orange-ball-fun-game-playground_376504-1206.jpg",
    },
    {
        id: 6,
        title: "Train Typing",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Train_Typing/contents/",
        banner: "https://via.placeholder.com/300x200?text=Train+Typing",
    },
    {
        id: 7,
        title: "Maze New",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Maze_New/contents/",
        banner: "https://static.vecteezy.com/system/resources/previews/014/008/164/non_2x/maze-game-template-in-camping-theme-for-kids-free-vector.jpg",
    },
    {
        id: 8,
        title: "Maze Runner",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Maze_runner/contents/",
        banner: "https://img.freepik.com/premium-vector/maze-game-kids-labyrinth-conundrum-color-vector-illustration_1057-172713.jpg",
    },
    {
        id: 9,
        title: "Mario Typing",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Mario_Typing/contents/",
        banner: "https://m.media-amazon.com/images/I/71RuXB-P8lL._AC_UF1000,1000_QL80_.jpg",
    },
    {
        id: 10,
        title: "Car-drive",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/Car_Drive/contents/",
        banner: "https://static.vecteezy.com/system/resources/thumbnails/050/358/009/small/a-slowmotion-closeup-as-the-flag-gently-waves-in-the-wind-the-nighttime-sky-and-bright-lights-creating-a-picturesque-backdrop-for-the-end-of-a-exhilarating-race-photo.jpg",
    },
    {
        id: 11,
        title: "WordConnect",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Scorm_Final_Activity_Template/WordConnect/contents/",
        banner: "https://via.placeholder.com/300x200?text=WordConnect",
    },
    {
        id: 12,
        title: "Abacus ",
        url: "http://10.4.40.172/Templates-2025/Abacus/contents/",
        banner: "/gameImg/abcus.png",
    },
    {
        id: 13,
        title: "ClickableWords ",
        url: "http://10.4.40.172/Templates-2025/MCQ-ClickableWords/contents/",
        banner: "https://cdn.splashmath.com/curriculum_uploads/images/playables/num_seq_photo_farm_2_gm.png",
    },
    {
        id: 14,
        title: "ComprehensionActivity ",
        url: "http://10.4.40.172/Templates-2025/ComprehensionActivitiy/contents/",
        banner: "https://cdn2.momjunction.com/wp-content/uploads/static-content/illustration_images/fun_english_learning_games_and_activities_for_kids_illustration.jpg.webp",
    },
    {
        id: 15,
        title: "CandyBurst ",
        url: "http://10.4.40.172/Templates-2025/Construct_games/Final_Activity_Template/CandyBurst/contents/",
        banner: "https://media.istockphoto.com/id/512397594/vector/scattered-sweet-candies.jpg?s=612x612&w=0&k=20&c=_fdp-W2zVevzWj85SkLG4vOBdKZ7jJMvt-2KpHkcFFY=",
    },
    {
        id: 16,
        title: "Infographic ",
        url: "http://10.4.40.172/Templates-2025/Infographic/contents/",
        banner: "https://www.janelbreitenstein.com/wp-content/uploads/2019/02/Learn-Through-Play-7-Skills-You-Can-Teach-Through-Fun-Activities-02-1-1024x648.png",
    },
    {
        id: 17,
        title: "MCQ-JumpingGame ",
        url: "http://10.4.40.172/Templates-2025/MCQ-JumpingGame/contents/",
        banner: "https://png.pngtree.com/thumb_back/fh260/back_our/20190620/ourmid/pngtree-children-go-to-school-study-fresh-blue-banner-image_150968.jpg",
    },
    {
        id: 18,
        title: "MCQ-Shoot ",
        url: "http://10.4.40.172/Templates-2025/MCQ-Shoot/contents/",
        banner: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJgNcKS537VP-eIzpT_9uwAVnJrI-teaub8E-jXpcG1QH9-YGbrd7VbKvFoloM4jG-GDU&usqp=CAU",
    },
    {
        id: 19,
        title: "MatchTheColumn ",
        url: "http://10.4.40.172/Templates-2025/MatchTheColumn-new/contents/",
        banner: "https://media.istockphoto.com/id/521305404/vector/matching-game-for-children-animals-and-favorite-food.jpg?s=612x612&w=0&k=20&c=Xsyj6K7diJPfOy_NNUPWDvFcYs4ldKRmLLnsa-TL54I=",
    },
    {
        id: 20,
        title: "SelectWords ",
        url: "http://10.4.40.172/Templates-2025/SelectWords/contents/",
        banner: "https://via.placeholder.com/300x200?text=Select+Words",
    },
    {
        id: 21,
        title: "SpotTheDifference ",
        url: "http://10.4.40.172/Templates-2025/Spotthedifference/contents/",
        banner: "https://via.placeholder.com/300x200?text=Spot+The+Difference",
    },
    {
        id: 22,
        title: "Typing ",
        url: "http://10.4.40.172/Templates-2025/Typing-Flashcard/contents/",
        banner: "https://via.placeholder.com/300x200?text=Typing+Game",
    },
    {
        id: 23,
        title: "WordSearch ",
        url: "http://10.4.40.172/Templates-2025/WordSearch/contents/",
        banner: "https://via.placeholder.com/300x200?text=Word+Search",
    },
    {
        id: 24,
        title: "ConnectLetter ",
        url: "http://10.4.40.172/Templates-2025/connectLetter/contents/",
        banner: "https://cdn.education.com/files/static/game-images/uppercase-letters-photoshoot-2022-12-13.jpg",
    },
    {
        id: 25,
        title: "CrossWord ",
        url: "http://10.4.40.172/Templates-2025/crossWord/contents/",
        banner: "https://static.vecteezy.com/system/resources/previews/041/061/356/non_2x/crossword-quiz-game-grid-with-galaxy-space-planets-vector.jpg",
    },
    {
        id: 26,
        title: "Slideshow ",
        url: "http://10.4.40.172/Templates-2025/slideshow/contents/",
        banner: "https://i.pinimg.com/736x/61/cf/5d/61cf5d07056151f6122eba38beb04dfd.jpg",
    },
    {
        id: 27,
        title: "Timeline ",
        url: "http://10.4.40.172/Templates-2025/timeline/contents/",
        banner: "https://static.vecteezy.com/system/resources/thumbnails/013/798/613/small_2x/the-view-of-playground-full-of-the-children-playing-on-it-vector.jpg",
    },
    {
        id: 28,
        title: "Type2shoot ",
        url: "http://10.4.40.172/Templates-2025/type2shoot/contents/",
        banner: "https://m.media-amazon.com/images/I/81zEm7Wm8sL._UF1000,1000_QL80_.jpg",
    },
    {
        id: 29,
        title: "Dictionary ",
        url: "http://10.4.40.172/Templates-2025/Dictionary/contents/",
        banner: "https://media.istockphoto.com/id/969053022/vector/educational-game-for-children-word-search-puzzle-kids-activity-summer-holidays-theme-learning.jpg?s=612x612&w=0&k=20&c=Ynuc5sILXtIJ2xtBssdhSSYeUMhdyp2uH34I56DrkIk=",
    },
    {
        id: 30,
        title: "ClickAndPlace Hotspot ",
        url: "http://10.4.40.172/Templates-2025/ClickAndPlace_placeholder/contents/",
        banner: "https://img.freepik.com/premium-vector/happy-kids-building-tower-with-colorful-blocks_150234-134259.jpg",
    },
    {
        id: 31,
        title: "Maze ",
        url: "http://10.4.40.172/Templates-2025/Maze/contents/",
        banner: "https://m.media-amazon.com/images/I/71wWsC1FNjL._AC_UF1000,1000_QL80_.jpg",
    },
    {
        id: 32,
        title: "Concept Map ",
        url: "http://10.4.40.172/Templates-2025/ConceptMap/contents/",
        banner: "https://static.vecteezy.com/system/resources/thumbnails/043/064/770/small/flat-style-family-board-game-for-children-kids-boardgame-with-green-map-game-steps-srat-and-finish-flowers-insects-ladybugs-and-grasshoppers-illustration-vector.jpg",
    },
    {
        id: 33,
        title: "Jumping Typing ",
        url: "http://10.4.40.172/Templates-2025/Typing-JumpingGame/contents/",
        banner: "https://as2.ftcdn.net/jpg/04/44/32/73/1000_F_444327300_YNdKVgCpB0tvsIGsepJopooKM6BWuynw.jpg",
    },
    {
        id: 34,
        title: "Click and Place category wise ",
        url: "http://10.4.40.172/Templates-2025/ClickNPlaceWithImageOrText/contents/",
        banner: "https://img.freepik.com/premium-photo/kids-play-together-kindergarden-playroom-with-children_1029476-224968.jpg",
    },
    {
        id: 35,
        title: "Interactive Map ",
        url: "http://10.4.40.172/Templates-2025/InteractiveMap/contents/",
        banner: "https://media.istockphoto.com/id/1288330715/vector/treasure-game-map-cartoon-tropical-island-map-showing-road-direction-to-pirate-gold-treasure.jpg?s=612x612&w=0&k=20&c=sYy7g1hkLwtqDErbpl2lrQItyvitxgY6AqTIY9s3LCk=",
    },
    {
        id: 36,
        title: "Colouring ",
        url: "http://10.4.40.172/Templates-2025/Coloring/contents/",
        banner: "https://play-lh.googleusercontent.com/Qv3LMRDdqAIXsgNDFQVT2h9FcuxTWCyzr_H5K9K0j8Tx1h88ea2YZGKAvMzRff2GbY8=w526-h296-rw",
    },
    {
        id: 37,
        title: "TG ",
        url: "http://10.4.40.172/Templates-2025/TG/",
        banner: "https://funlearningforkids.com/wp-content/uploads/2016/02/I-Have-Who-Has-Card-Game-Blank-Sight-Words-Alphabet-FB.png",
    },
    {
        id: 38,
        title: "Conversation Practice ",
        url: "http://10.4.40.172/Templates-2025/ConversationPractice/contents/",
        banner: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwrJZDE7Z5f5xjRV_h15Vfs3KL7vorKcNnvQ&s",
    },
    {
        id: 39,
        title: "Quiz ",
        url: "http://10.4.40.172/Templates-2025/quiz/contents/",
        banner: "https://img.freepik.com/free-vector/purple-background-with-quiz-word-colorful-people_52683-126.jpg",
    },
    {
        id: 40,
        title: "MCQ-LongOptionType ",
        url: "http://10.4.40.172/Templates-2025/MCQ-LongOptionType/contents/",
        banner: "https://static.vecteezy.com/system/resources/thumbnails/010/876/471/small/quiz-questions-and-test-menu-choice-neon-template-vector.jpg",
    },
    {
        id: 41,
        title: "Hots - Type ",
        url: "http://10.4.40.172/Templates-2025/HOTS-Typing/contents/",
        banner: "https://m.media-amazon.com/images/I/71QzeycflWL.jpg",
    },
];

export default gamesData;